rooms:
  - '!someroom:example.com'
  - '!otherroom:example.com'

# add a room ID here to send a message to when someone joins the above rooms
# (optional)
notification_room: 

# you can use {user} to reference the joining userID in this message
message: |
    Welcome {user}! Please be sure to read the topic for helpful links and information.
